'use strict';
/* THE load order, in one place. index.html loads these in sequence; sw.js precaches the same list.
   Rule of thumb: data before the systems that read it, systems before the UI that draws them,
   screens after the UI helpers they use, main.js last. Function calls across files are fine in any
   order (they run after everything has loaded); only top-level constants care about order. */
const MCV_MODULES = [
  // core + data (no game state)
  'core/util.js',
  'core/display.js',
  // text: language module, then one table per language (en = master). Data files below use tl().
  'i18n/i18n.js',
  'i18n/en.js',
  'i18n/es.js',
  'i18n/fr.js',
  'i18n/de.js',
  'i18n/it.js',
  'i18n/pt.js',
  'i18n/pl.js',
  'i18n/tr.js',
  'i18n/uk.js',
  'i18n/ru.js',
  'i18n/zh.js',
  'i18n/ja.js',
  'i18n/ko.js',
  'art/palette.js',
  'art/font.js',
  'data/config.js',
  'data/events.js',
  'data/vehicles.js',
  'data/powerups.js',
  'data/comps.js',
  'data/cosmetics.js',
  'data/goals.js',
  'data/products.js',
  // hotels (levels): registry first, then one file per hotel in menu order
  'data/hotels/registry.js',
  'data/hotels/monte_carlo.js',
  'data/hotels/las_vegas.js',
  'data/hotels/dubai.js',
  'data/hotels/swiss_chalet.js',
  // art + audio
  'art/sprites.js',
  'art/cars.js',
  'audio/sound.js',
  // world: geometry, routing, lot model, jobs (plan + run)
  'world/geometry.js',
  'world/routing.js',
  'world/lot.js',
  'world/premium.js',
  'world/workers.js',
  'world/jobs.js',
  'world/planner.js',
  'world/runner.js',
  // career (persistent)
  'career/save.js',
  'career/store.js',
  'career/progression.js',
  'career/roster.js',
  // simulation rules (one shift)
  'sim/state.js',
  'sim/fx.js',
  'sim/waves.js',
  'sim/patience.js',
  'sim/economy.js',
  'sim/heat.js',
  'sim/powerups.js',
  'sim/reserved.js',
  'sim/arrivals.js',
  'sim/guests.js',
  'sim/comps.js',
  'sim/movers.js',
  'sim/helicopter.js',
  'sim/goals.js',
  'sim/crew.js',
  'sim/shift.js',
  'sim/commands.js',
  'sim/step.js',
  'tutorial/tutorial.js',
  // rendering + in-game UI
  'ui/canvas.js',
  'ui/widgets.js',
  'render/background.js',
  'render/crowd.js',
  'render/helicopter.js',
  'render/people.js',
  'render/premium.js',
  'render/game.js',
  'ui/hud.js',
  'ui/board.js',
  'ui/messages.js',
  'ui/comp_menu.js',
  'ui/crew_panel.js',
  'ui/selection.js',
  'ui/input.js',
  'ui/debug.js',
  // screens + app
  'screens/registry.js',
  'screens/title.js',
  'screens/settings.js',
  'screens/language.js',
  'screens/debug_menu.js',
  'screens/howto.js',
  'screens/vehicle_guide.js',
  'screens/hotels.js',
  'screens/shift_prep.js',
  'screens/promotion.js',
  'screens/summary.js',
  'screens/game.js',
  'events/director.js',
  'events/actions.js',
  'events/drunk_driver.js',
  'events/joyride.js',
  'app/flow.js',
  'main.js',
];
if (typeof module !== 'undefined') module.exports = MCV_MODULES; // lets node tooling read the list
